/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface HarvestListing {
    id: bigint;
    readinessScore: number;
    diagnosis?: CropAnalysisReport;
    quantity: bigint;
    cropType: string;
    qualityCertificate: boolean;
    harvestDate: Time;
    daysPassed: bigint;
    location: string;
    farmer: Principal;
    totalGrowthCycle: bigint;
}
export interface TransportOffer {
    vehicleType: VehicleType;
    transporter: Principal;
    listingId: bigint;
    commitmentId: bigint;
    routeEnd: string;
    estimatedDeliveryTime: string;
    trackingStatus: string;
    loadCapacity: bigint;
    routeStart: string;
    currentLocation: string;
    accepted: boolean;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface RouteLocation {
    quantity: bigint;
    location: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PredictYieldResult {
    predictedPrice: number;
    predictedYield: number;
}
export interface OptimizedRoute {
    deliveryLocations: Array<RouteLocation>;
    costSavings: number;
    distance: number;
    pickupLocations: Array<RouteLocation>;
}
export interface Commitment {
    id: bigint;
    listingId: bigint;
    quantity: bigint;
    buyer: Principal;
    price: bigint;
}
export type VehicleType = {
    __kind__: "Van";
    Van: null;
} | {
    __kind__: "Bike";
    Bike: null;
} | {
    __kind__: "Truck";
    Truck: null;
} | {
    __kind__: "Other";
    Other: string;
};
export interface Disease {
    name: string;
    severity: bigint;
}
export interface ParsedHarvestData {
    quantity: bigint;
    cropType: string;
    harvestDate: bigint;
    location: string;
}
export interface ListingFilterCriteria {
    minReadinessScore?: number;
    qualityCertificateRequired?: boolean;
    cropType?: string;
    location?: string;
}
export interface BuyerDemand {
    id: bigint;
    status: string;
    createdAt: Time;
    pricePerKg: bigint;
    linkedListing?: bigint;
    buyerId: Principal;
    quantity: bigint;
    cropType: string;
    destinationSupply: string;
}
export interface CropAnalysisReport {
    harvestReadinessScore: number;
    healthFactors: {
        nutrientDeficiencies: Array<NutrientDeficiency>;
        pestDetection: boolean;
        diseases: Array<Disease>;
    };
    qualityGrade: Variant_Premium_Reject_Standard;
}
export interface NutrientDeficiency {
    impact: bigint;
    name: string;
}
export interface UserProfile {
    contact: string;
    appRole: AppRole;
    name: string;
    location: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AppRole {
    Transporter = "Transporter",
    Farmer = "Farmer",
    Buyer = "Buyer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_Premium_Reject_Standard {
    Premium = "Premium",
    Reject = "Reject",
    Standard = "Standard"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptBuyerDemand(demandId: bigint, listingId: bigint): Promise<void>;
    acceptTransportOffer(listingId: bigint, transporter: Principal, commitmentId: bigint): Promise<void>;
    analyzeCropMaturity(_image: Uint8Array): Promise<number>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateReadinessScore(daysPassed: bigint, totalGrowthCycle: bigint, cropType: string, location: string, farmerAssessmentScore: number): Promise<number>;
    createBuyerDemand(cropType: string, quantity: bigint, pricePerKg: bigint, destinationSupply: string): Promise<bigint>;
    createHarvestListing(cropType: string, quantity: bigint, harvestDate: Time, location: string, readinessScore: number, qualityCertificate: boolean, daysPassed: bigint, totalGrowthCycle: bigint): Promise<bigint>;
    deleteListing(listingId: bigint): Promise<void>;
    diagnoseCrop(listingId: bigint, _image: Uint8Array): Promise<CropAnalysisReport>;
    filterListings(criteria: ListingFilterCriteria): Promise<Array<HarvestListing>>;
    getAllBuyerDemands(): Promise<Array<BuyerDemand>>;
    getAvailableListings(): Promise<Array<HarvestListing>>;
    getBuyerDemands(): Promise<Array<BuyerDemand>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCommitments(listingId: bigint): Promise<Array<Commitment>>;
    getCommitmentsByBuyer(): Promise<Array<Commitment>>;
    getListingDetails(listingId: bigint): Promise<HarvestListing>;
    getSortedCommitments(listingId: bigint): Promise<Array<Commitment>>;
    getSortedListings(): Promise<Array<HarvestListing>>;
    getTransportOffers(listingId: bigint): Promise<Array<TransportOffer>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    makeCommitment(listingId: bigint, quantity: bigint, price: bigint): Promise<bigint>;
    makeTransportOffer(listingId: bigint, vehicleType: VehicleType, loadCapacity: bigint, routeStart: string, routeEnd: string): Promise<void>;
    optimizeLogisticsRoutes(vehicleCapacity: bigint, vehicleType: VehicleType, startLocation: string, deliveryLocation: string): Promise<Array<OptimizedRoute>>;
    parseHarvestInput(_rawInput: string): Promise<ParsedHarvestData>;
    predictYieldAndPrice(cropType: string, location: string, daysPassed: bigint, totalGrowthCycle: bigint, quantity: bigint): Promise<PredictYieldResult>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchListingsByCrop(cropType: string): Promise<Array<HarvestListing>>;
    updateTracking(listingId: bigint, currentLocation: string, estimatedDeliveryTime: string, trackingStatus: string): Promise<void>;
}
import type { AppRole as _AppRole, BuyerDemand as _BuyerDemand, CropAnalysisReport as _CropAnalysisReport, Disease as _Disease, HarvestListing as _HarvestListing, ListingFilterCriteria as _ListingFilterCriteria, NutrientDeficiency as _NutrientDeficiency, Time as _Time, TransportOffer as _TransportOffer, UserProfile as _UserProfile, UserRole as _UserRole, VehicleType as _VehicleType, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptBuyerDemand(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptBuyerDemand(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptBuyerDemand(arg0, arg1);
            return result;
        }
    }
    async acceptTransportOffer(arg0: bigint, arg1: Principal, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptTransportOffer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptTransportOffer(arg0, arg1, arg2);
            return result;
        }
    }
    async analyzeCropMaturity(arg0: Uint8Array): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeCropMaturity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeCropMaturity(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateReadinessScore(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: number): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateReadinessScore(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateReadinessScore(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createBuyerDemand(arg0: string, arg1: bigint, arg2: bigint, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBuyerDemand(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBuyerDemand(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createHarvestListing(arg0: string, arg1: bigint, arg2: Time, arg3: string, arg4: number, arg5: boolean, arg6: bigint, arg7: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createHarvestListing(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHarvestListing(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async deleteListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async diagnoseCrop(arg0: bigint, arg1: Uint8Array): Promise<CropAnalysisReport> {
        if (this.processError) {
            try {
                const result = await this.actor.diagnoseCrop(arg0, arg1);
                return from_candid_CropAnalysisReport_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.diagnoseCrop(arg0, arg1);
            return from_candid_CropAnalysisReport_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterListings(arg0: ListingFilterCriteria): Promise<Array<HarvestListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterListings(to_candid_ListingFilterCriteria_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterListings(to_candid_ListingFilterCriteria_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBuyerDemands(): Promise<Array<BuyerDemand>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBuyerDemands();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBuyerDemands();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableListings(): Promise<Array<HarvestListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableListings();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableListings();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBuyerDemands(): Promise<Array<BuyerDemand>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuyerDemands();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuyerDemands();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommitments(arg0: bigint): Promise<Array<Commitment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommitments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommitments(arg0);
            return result;
        }
    }
    async getCommitmentsByBuyer(): Promise<Array<Commitment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommitmentsByBuyer();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommitmentsByBuyer();
            return result;
        }
    }
    async getListingDetails(arg0: bigint): Promise<HarvestListing> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingDetails(arg0);
                return from_candid_HarvestListing_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingDetails(arg0);
            return from_candid_HarvestListing_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSortedCommitments(arg0: bigint): Promise<Array<Commitment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedCommitments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedCommitments(arg0);
            return result;
        }
    }
    async getSortedListings(): Promise<Array<HarvestListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedListings();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedListings();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransportOffers(arg0: bigint): Promise<Array<TransportOffer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransportOffers(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransportOffers(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async makeCommitment(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.makeCommitment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.makeCommitment(arg0, arg1, arg2);
            return result;
        }
    }
    async makeTransportOffer(arg0: bigint, arg1: VehicleType, arg2: bigint, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.makeTransportOffer(arg0, to_candid_VehicleType_n34(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.makeTransportOffer(arg0, to_candid_VehicleType_n34(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async optimizeLogisticsRoutes(arg0: bigint, arg1: VehicleType, arg2: string, arg3: string): Promise<Array<OptimizedRoute>> {
        if (this.processError) {
            try {
                const result = await this.actor.optimizeLogisticsRoutes(arg0, to_candid_VehicleType_n34(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.optimizeLogisticsRoutes(arg0, to_candid_VehicleType_n34(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async parseHarvestInput(arg0: string): Promise<ParsedHarvestData> {
        if (this.processError) {
            try {
                const result = await this.actor.parseHarvestInput(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.parseHarvestInput(arg0);
            return result;
        }
    }
    async predictYieldAndPrice(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint): Promise<PredictYieldResult> {
        if (this.processError) {
            try {
                const result = await this.actor.predictYieldAndPrice(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.predictYieldAndPrice(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchListingsByCrop(arg0: string): Promise<Array<HarvestListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchListingsByCrop(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchListingsByCrop(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTracking(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTracking(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTracking(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_AppRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_BuyerDemand_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BuyerDemand): BuyerDemand {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_CropAnalysisReport_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CropAnalysisReport): CropAnalysisReport {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_HarvestListing_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HarvestListing): HarvestListing {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_TransportOffer_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransportOffer): TransportOffer {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleType): VehicleType {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CropAnalysisReport]): CropAnalysisReport | null {
    return value.length === 0 ? null : from_candid_CropAnalysisReport_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    harvestReadinessScore: number;
    healthFactors: {
        nutrientDeficiencies: Array<_NutrientDeficiency>;
        pestDetection: boolean;
        diseases: Array<_Disease>;
    };
    qualityGrade: {
        Premium: null;
    } | {
        Reject: null;
    } | {
        Standard: null;
    };
}): {
    harvestReadinessScore: number;
    healthFactors: {
        nutrientDeficiencies: Array<NutrientDeficiency>;
        pestDetection: boolean;
        diseases: Array<Disease>;
    };
    qualityGrade: Variant_Premium_Reject_Standard;
} {
    return {
        harvestReadinessScore: value.harvestReadinessScore,
        healthFactors: value.healthFactors,
        qualityGrade: from_candid_variant_n12(_uploadFile, _downloadFile, value.qualityGrade)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    readinessScore: number;
    diagnosis: [] | [_CropAnalysisReport];
    quantity: bigint;
    cropType: string;
    qualityCertificate: boolean;
    harvestDate: _Time;
    daysPassed: bigint;
    location: string;
    farmer: Principal;
    totalGrowthCycle: bigint;
}): {
    id: bigint;
    readinessScore: number;
    diagnosis?: CropAnalysisReport;
    quantity: bigint;
    cropType: string;
    qualityCertificate: boolean;
    harvestDate: Time;
    daysPassed: bigint;
    location: string;
    farmer: Principal;
    totalGrowthCycle: bigint;
} {
    return {
        id: value.id,
        readinessScore: value.readinessScore,
        diagnosis: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.diagnosis)),
        quantity: value.quantity,
        cropType: value.cropType,
        qualityCertificate: value.qualityCertificate,
        harvestDate: value.harvestDate,
        daysPassed: value.daysPassed,
        location: value.location,
        farmer: value.farmer,
        totalGrowthCycle: value.totalGrowthCycle
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    createdAt: _Time;
    pricePerKg: bigint;
    linkedListing: [] | [bigint];
    buyerId: Principal;
    quantity: bigint;
    cropType: string;
    destinationSupply: string;
}): {
    id: bigint;
    status: string;
    createdAt: Time;
    pricePerKg: bigint;
    linkedListing?: bigint;
    buyerId: Principal;
    quantity: bigint;
    cropType: string;
    destinationSupply: string;
} {
    return {
        id: value.id,
        status: value.status,
        createdAt: value.createdAt,
        pricePerKg: value.pricePerKg,
        linkedListing: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.linkedListing)),
        buyerId: value.buyerId,
        quantity: value.quantity,
        cropType: value.cropType,
        destinationSupply: value.destinationSupply
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact: string;
    appRole: _AppRole;
    name: string;
    location: string;
}): {
    contact: string;
    appRole: AppRole;
    name: string;
    location: string;
} {
    return {
        contact: value.contact,
        appRole: from_candid_AppRole_n25(_uploadFile, _downloadFile, value.appRole),
        name: value.name,
        location: value.location
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vehicleType: _VehicleType;
    transporter: Principal;
    listingId: bigint;
    commitmentId: bigint;
    routeEnd: string;
    estimatedDeliveryTime: string;
    trackingStatus: string;
    loadCapacity: bigint;
    routeStart: string;
    currentLocation: string;
    accepted: boolean;
}): {
    vehicleType: VehicleType;
    transporter: Principal;
    listingId: bigint;
    commitmentId: bigint;
    routeEnd: string;
    estimatedDeliveryTime: string;
    trackingStatus: string;
    loadCapacity: bigint;
    routeStart: string;
    currentLocation: string;
    accepted: boolean;
} {
    return {
        vehicleType: from_candid_VehicleType_n32(_uploadFile, _downloadFile, value.vehicleType),
        transporter: value.transporter,
        listingId: value.listingId,
        commitmentId: value.commitmentId,
        routeEnd: value.routeEnd,
        estimatedDeliveryTime: value.estimatedDeliveryTime,
        trackingStatus: value.trackingStatus,
        loadCapacity: value.loadCapacity,
        routeStart: value.routeStart,
        currentLocation: value.currentLocation,
        accepted: value.accepted
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Premium: null;
} | {
    Reject: null;
} | {
    Standard: null;
}): Variant_Premium_Reject_Standard {
    return "Premium" in value ? Variant_Premium_Reject_Standard.Premium : "Reject" in value ? Variant_Premium_Reject_Standard.Reject : "Standard" in value ? Variant_Premium_Reject_Standard.Standard : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Transporter: null;
} | {
    Farmer: null;
} | {
    Buyer: null;
}): AppRole {
    return "Transporter" in value ? AppRole.Transporter : "Farmer" in value ? AppRole.Farmer : "Buyer" in value ? AppRole.Buyer : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Van: null;
} | {
    Bike: null;
} | {
    Truck: null;
} | {
    Other: string;
}): {
    __kind__: "Van";
    Van: null;
} | {
    __kind__: "Bike";
    Bike: null;
} | {
    __kind__: "Truck";
    Truck: null;
} | {
    __kind__: "Other";
    Other: string;
} {
    return "Van" in value ? {
        __kind__: "Van",
        Van: value.Van
    } : "Bike" in value ? {
        __kind__: "Bike",
        Bike: value.Bike
    } : "Truck" in value ? {
        __kind__: "Truck",
        Truck: value.Truck
    } : "Other" in value ? {
        __kind__: "Other",
        Other: value.Other
    } : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HarvestListing>): Array<HarvestListing> {
    return value.map((x)=>from_candid_HarvestListing_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BuyerDemand>): Array<BuyerDemand> {
    return value.map((x)=>from_candid_BuyerDemand_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransportOffer>): Array<TransportOffer> {
    return value.map((x)=>from_candid_TransportOffer_n30(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_ListingFilterCriteria_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingFilterCriteria): _ListingFilterCriteria {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): _VehicleType {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minReadinessScore?: number;
    qualityCertificateRequired?: boolean;
    cropType?: string;
    location?: string;
}): {
    minReadinessScore: [] | [number];
    qualityCertificateRequired: [] | [boolean];
    cropType: [] | [string];
    location: [] | [string];
} {
    return {
        minReadinessScore: value.minReadinessScore ? candid_some(value.minReadinessScore) : candid_none(),
        qualityCertificateRequired: value.qualityCertificateRequired ? candid_some(value.qualityCertificateRequired) : candid_none(),
        cropType: value.cropType ? candid_some(value.cropType) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact: string;
    appRole: AppRole;
    name: string;
    location: string;
}): {
    contact: string;
    appRole: _AppRole;
    name: string;
    location: string;
} {
    return {
        contact: value.contact,
        appRole: to_candid_AppRole_n38(_uploadFile, _downloadFile, value.appRole),
        name: value.name,
        location: value.location
    };
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "Van";
    Van: null;
} | {
    __kind__: "Bike";
    Bike: null;
} | {
    __kind__: "Truck";
    Truck: null;
} | {
    __kind__: "Other";
    Other: string;
}): {
    Van: null;
} | {
    Bike: null;
} | {
    Truck: null;
} | {
    Other: string;
} {
    return value.__kind__ === "Van" ? {
        Van: value.Van
    } : value.__kind__ === "Bike" ? {
        Bike: value.Bike
    } : value.__kind__ === "Truck" ? {
        Truck: value.Truck
    } : value.__kind__ === "Other" ? {
        Other: value.Other
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    Transporter: null;
} | {
    Farmer: null;
} | {
    Buyer: null;
} {
    return value == AppRole.Transporter ? {
        Transporter: null
    } : value == AppRole.Farmer ? {
        Farmer: null
    } : value == AppRole.Buyer ? {
        Buyer: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
