/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const NutrientDeficiency = IDL.Record({
  'impact' : IDL.Int,
  'name' : IDL.Text,
});
export const Disease = IDL.Record({ 'name' : IDL.Text, 'severity' : IDL.Int });
export const CropAnalysisReport = IDL.Record({
  'harvestReadinessScore' : IDL.Float64,
  'healthFactors' : IDL.Record({
    'nutrientDeficiencies' : IDL.Vec(NutrientDeficiency),
    'pestDetection' : IDL.Bool,
    'diseases' : IDL.Vec(Disease),
  }),
  'qualityGrade' : IDL.Variant({
    'Premium' : IDL.Null,
    'Reject' : IDL.Null,
    'Standard' : IDL.Null,
  }),
});
export const ListingFilterCriteria = IDL.Record({
  'minReadinessScore' : IDL.Opt(IDL.Float64),
  'qualityCertificateRequired' : IDL.Opt(IDL.Bool),
  'cropType' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});
export const HarvestListing = IDL.Record({
  'id' : IDL.Nat,
  'readinessScore' : IDL.Float64,
  'diagnosis' : IDL.Opt(CropAnalysisReport),
  'quantity' : IDL.Nat,
  'cropType' : IDL.Text,
  'qualityCertificate' : IDL.Bool,
  'harvestDate' : Time,
  'daysPassed' : IDL.Nat,
  'location' : IDL.Text,
  'farmer' : IDL.Principal,
  'totalGrowthCycle' : IDL.Nat,
});
export const BuyerDemand = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'createdAt' : Time,
  'pricePerKg' : IDL.Nat,
  'linkedListing' : IDL.Opt(IDL.Nat),
  'buyerId' : IDL.Principal,
  'quantity' : IDL.Nat,
  'cropType' : IDL.Text,
  'destinationSupply' : IDL.Text,
});
export const AppRole = IDL.Variant({
  'Transporter' : IDL.Null,
  'Farmer' : IDL.Null,
  'Buyer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'contact' : IDL.Text,
  'appRole' : AppRole,
  'name' : IDL.Text,
  'location' : IDL.Text,
});
export const Commitment = IDL.Record({
  'id' : IDL.Nat,
  'listingId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'buyer' : IDL.Principal,
  'price' : IDL.Nat,
});
export const VehicleType = IDL.Variant({
  'Van' : IDL.Null,
  'Bike' : IDL.Null,
  'Truck' : IDL.Null,
  'Other' : IDL.Text,
});
export const TransportOffer = IDL.Record({
  'vehicleType' : VehicleType,
  'transporter' : IDL.Principal,
  'listingId' : IDL.Nat,
  'commitmentId' : IDL.Nat,
  'routeEnd' : IDL.Text,
  'estimatedDeliveryTime' : IDL.Text,
  'trackingStatus' : IDL.Text,
  'loadCapacity' : IDL.Nat,
  'routeStart' : IDL.Text,
  'currentLocation' : IDL.Text,
  'accepted' : IDL.Bool,
});
export const RouteLocation = IDL.Record({
  'quantity' : IDL.Nat,
  'location' : IDL.Text,
});
export const OptimizedRoute = IDL.Record({
  'deliveryLocations' : IDL.Vec(RouteLocation),
  'costSavings' : IDL.Float64,
  'distance' : IDL.Float64,
  'pickupLocations' : IDL.Vec(RouteLocation),
});
export const ParsedHarvestData = IDL.Record({
  'quantity' : IDL.Nat,
  'cropType' : IDL.Text,
  'harvestDate' : IDL.Int,
  'location' : IDL.Text,
});
export const PredictYieldResult = IDL.Record({
  'predictedPrice' : IDL.Float64,
  'predictedYield' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptBuyerDemand' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'acceptTransportOffer' : IDL.Func([IDL.Nat, IDL.Principal, IDL.Nat], [], []),
  'analyzeCropMaturity' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Float64],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateReadinessScore' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Float64],
      [],
    ),
  'createBuyerDemand' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createHarvestListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        Time,
        IDL.Text,
        IDL.Float64,
        IDL.Bool,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteListing' : IDL.Func([IDL.Nat], [], []),
  'diagnoseCrop' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat8)],
      [CropAnalysisReport],
      [],
    ),
  'filterListings' : IDL.Func(
      [ListingFilterCriteria],
      [IDL.Vec(HarvestListing)],
      ['query'],
    ),
  'getAllBuyerDemands' : IDL.Func([], [IDL.Vec(BuyerDemand)], ['query']),
  'getAvailableListings' : IDL.Func([], [IDL.Vec(HarvestListing)], ['query']),
  'getBuyerDemands' : IDL.Func([], [IDL.Vec(BuyerDemand)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommitments' : IDL.Func([IDL.Nat], [IDL.Vec(Commitment)], ['query']),
  'getCommitmentsByBuyer' : IDL.Func([], [IDL.Vec(Commitment)], ['query']),
  'getListingDetails' : IDL.Func([IDL.Nat], [HarvestListing], ['query']),
  'getSortedCommitments' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Commitment)],
      ['query'],
    ),
  'getSortedListings' : IDL.Func([], [IDL.Vec(HarvestListing)], ['query']),
  'getTransportOffers' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TransportOffer)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'makeCommitment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'makeTransportOffer' : IDL.Func(
      [IDL.Nat, VehicleType, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'optimizeLogisticsRoutes' : IDL.Func(
      [IDL.Nat, VehicleType, IDL.Text, IDL.Text],
      [IDL.Vec(OptimizedRoute)],
      [],
    ),
  'parseHarvestInput' : IDL.Func([IDL.Text], [ParsedHarvestData], ['query']),
  'predictYieldAndPrice' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [PredictYieldResult],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchListingsByCrop' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HarvestListing)],
      ['query'],
    ),
  'updateTracking' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const NutrientDeficiency = IDL.Record({
    'impact' : IDL.Int,
    'name' : IDL.Text,
  });
  const Disease = IDL.Record({ 'name' : IDL.Text, 'severity' : IDL.Int });
  const CropAnalysisReport = IDL.Record({
    'harvestReadinessScore' : IDL.Float64,
    'healthFactors' : IDL.Record({
      'nutrientDeficiencies' : IDL.Vec(NutrientDeficiency),
      'pestDetection' : IDL.Bool,
      'diseases' : IDL.Vec(Disease),
    }),
    'qualityGrade' : IDL.Variant({
      'Premium' : IDL.Null,
      'Reject' : IDL.Null,
      'Standard' : IDL.Null,
    }),
  });
  const ListingFilterCriteria = IDL.Record({
    'minReadinessScore' : IDL.Opt(IDL.Float64),
    'qualityCertificateRequired' : IDL.Opt(IDL.Bool),
    'cropType' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  const HarvestListing = IDL.Record({
    'id' : IDL.Nat,
    'readinessScore' : IDL.Float64,
    'diagnosis' : IDL.Opt(CropAnalysisReport),
    'quantity' : IDL.Nat,
    'cropType' : IDL.Text,
    'qualityCertificate' : IDL.Bool,
    'harvestDate' : Time,
    'daysPassed' : IDL.Nat,
    'location' : IDL.Text,
    'farmer' : IDL.Principal,
    'totalGrowthCycle' : IDL.Nat,
  });
  const BuyerDemand = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'createdAt' : Time,
    'pricePerKg' : IDL.Nat,
    'linkedListing' : IDL.Opt(IDL.Nat),
    'buyerId' : IDL.Principal,
    'quantity' : IDL.Nat,
    'cropType' : IDL.Text,
    'destinationSupply' : IDL.Text,
  });
  const AppRole = IDL.Variant({
    'Transporter' : IDL.Null,
    'Farmer' : IDL.Null,
    'Buyer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'contact' : IDL.Text,
    'appRole' : AppRole,
    'name' : IDL.Text,
    'location' : IDL.Text,
  });
  const Commitment = IDL.Record({
    'id' : IDL.Nat,
    'listingId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'buyer' : IDL.Principal,
    'price' : IDL.Nat,
  });
  const VehicleType = IDL.Variant({
    'Van' : IDL.Null,
    'Bike' : IDL.Null,
    'Truck' : IDL.Null,
    'Other' : IDL.Text,
  });
  const TransportOffer = IDL.Record({
    'vehicleType' : VehicleType,
    'transporter' : IDL.Principal,
    'listingId' : IDL.Nat,
    'commitmentId' : IDL.Nat,
    'routeEnd' : IDL.Text,
    'estimatedDeliveryTime' : IDL.Text,
    'trackingStatus' : IDL.Text,
    'loadCapacity' : IDL.Nat,
    'routeStart' : IDL.Text,
    'currentLocation' : IDL.Text,
    'accepted' : IDL.Bool,
  });
  const RouteLocation = IDL.Record({
    'quantity' : IDL.Nat,
    'location' : IDL.Text,
  });
  const OptimizedRoute = IDL.Record({
    'deliveryLocations' : IDL.Vec(RouteLocation),
    'costSavings' : IDL.Float64,
    'distance' : IDL.Float64,
    'pickupLocations' : IDL.Vec(RouteLocation),
  });
  const ParsedHarvestData = IDL.Record({
    'quantity' : IDL.Nat,
    'cropType' : IDL.Text,
    'harvestDate' : IDL.Int,
    'location' : IDL.Text,
  });
  const PredictYieldResult = IDL.Record({
    'predictedPrice' : IDL.Float64,
    'predictedYield' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptBuyerDemand' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'acceptTransportOffer' : IDL.Func(
        [IDL.Nat, IDL.Principal, IDL.Nat],
        [],
        [],
      ),
    'analyzeCropMaturity' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Float64],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateReadinessScore' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Float64],
        [],
      ),
    'createBuyerDemand' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createHarvestListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          Time,
          IDL.Text,
          IDL.Float64,
          IDL.Bool,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteListing' : IDL.Func([IDL.Nat], [], []),
    'diagnoseCrop' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat8)],
        [CropAnalysisReport],
        [],
      ),
    'filterListings' : IDL.Func(
        [ListingFilterCriteria],
        [IDL.Vec(HarvestListing)],
        ['query'],
      ),
    'getAllBuyerDemands' : IDL.Func([], [IDL.Vec(BuyerDemand)], ['query']),
    'getAvailableListings' : IDL.Func([], [IDL.Vec(HarvestListing)], ['query']),
    'getBuyerDemands' : IDL.Func([], [IDL.Vec(BuyerDemand)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommitments' : IDL.Func([IDL.Nat], [IDL.Vec(Commitment)], ['query']),
    'getCommitmentsByBuyer' : IDL.Func([], [IDL.Vec(Commitment)], ['query']),
    'getListingDetails' : IDL.Func([IDL.Nat], [HarvestListing], ['query']),
    'getSortedCommitments' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Commitment)],
        ['query'],
      ),
    'getSortedListings' : IDL.Func([], [IDL.Vec(HarvestListing)], ['query']),
    'getTransportOffers' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TransportOffer)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'makeCommitment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'makeTransportOffer' : IDL.Func(
        [IDL.Nat, VehicleType, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'optimizeLogisticsRoutes' : IDL.Func(
        [IDL.Nat, VehicleType, IDL.Text, IDL.Text],
        [IDL.Vec(OptimizedRoute)],
        [],
      ),
    'parseHarvestInput' : IDL.Func([IDL.Text], [ParsedHarvestData], ['query']),
    'predictYieldAndPrice' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [PredictYieldResult],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchListingsByCrop' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HarvestListing)],
        ['query'],
      ),
    'updateTracking' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };