/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'Transporter' : null } |
  { 'Farmer' : null } |
  { 'Buyer' : null };
export interface BuyerDemand {
  'id' : bigint,
  'status' : string,
  'createdAt' : Time,
  'pricePerKg' : bigint,
  'linkedListing' : [] | [bigint],
  'buyerId' : Principal,
  'quantity' : bigint,
  'cropType' : string,
  'destinationSupply' : string,
}
export interface Commitment {
  'id' : bigint,
  'listingId' : bigint,
  'quantity' : bigint,
  'buyer' : Principal,
  'price' : bigint,
}
export interface CropAnalysisReport {
  'harvestReadinessScore' : number,
  'healthFactors' : {
    'nutrientDeficiencies' : Array<NutrientDeficiency>,
    'pestDetection' : boolean,
    'diseases' : Array<Disease>,
  },
  'qualityGrade' : { 'Premium' : null } |
    { 'Reject' : null } |
    { 'Standard' : null },
}
export interface Disease { 'name' : string, 'severity' : bigint }
export interface HarvestListing {
  'id' : bigint,
  'readinessScore' : number,
  'diagnosis' : [] | [CropAnalysisReport],
  'quantity' : bigint,
  'cropType' : string,
  'qualityCertificate' : boolean,
  'harvestDate' : Time,
  'daysPassed' : bigint,
  'location' : string,
  'farmer' : Principal,
  'totalGrowthCycle' : bigint,
}
export interface ListingFilterCriteria {
  'minReadinessScore' : [] | [number],
  'qualityCertificateRequired' : [] | [boolean],
  'cropType' : [] | [string],
  'location' : [] | [string],
}
export interface NutrientDeficiency { 'impact' : bigint, 'name' : string }
export interface OptimizedRoute {
  'deliveryLocations' : Array<RouteLocation>,
  'costSavings' : number,
  'distance' : number,
  'pickupLocations' : Array<RouteLocation>,
}
export interface ParsedHarvestData {
  'quantity' : bigint,
  'cropType' : string,
  'harvestDate' : bigint,
  'location' : string,
}
export interface PredictYieldResult {
  'predictedPrice' : number,
  'predictedYield' : number,
}
export interface RouteLocation { 'quantity' : bigint, 'location' : string }
export type Time = bigint;
export interface TransportOffer {
  'vehicleType' : VehicleType,
  'transporter' : Principal,
  'listingId' : bigint,
  'commitmentId' : bigint,
  'routeEnd' : string,
  'estimatedDeliveryTime' : string,
  'trackingStatus' : string,
  'loadCapacity' : bigint,
  'routeStart' : string,
  'currentLocation' : string,
  'accepted' : boolean,
}
export interface UserProfile {
  'contact' : string,
  'appRole' : AppRole,
  'name' : string,
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VehicleType = { 'Van' : null } |
  { 'Bike' : null } |
  { 'Truck' : null } |
  { 'Other' : string };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptBuyerDemand' : ActorMethod<[bigint, bigint], undefined>,
  'acceptTransportOffer' : ActorMethod<[bigint, Principal, bigint], undefined>,
  'analyzeCropMaturity' : ActorMethod<[Uint8Array], number>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateReadinessScore' : ActorMethod<
    [bigint, bigint, string, string, number],
    number
  >,
  'createBuyerDemand' : ActorMethod<[string, bigint, bigint, string], bigint>,
  'createHarvestListing' : ActorMethod<
    [string, bigint, Time, string, number, boolean, bigint, bigint],
    bigint
  >,
  'deleteListing' : ActorMethod<[bigint], undefined>,
  'diagnoseCrop' : ActorMethod<[bigint, Uint8Array], CropAnalysisReport>,
  'filterListings' : ActorMethod<
    [ListingFilterCriteria],
    Array<HarvestListing>
  >,
  'getAllBuyerDemands' : ActorMethod<[], Array<BuyerDemand>>,
  'getAvailableListings' : ActorMethod<[], Array<HarvestListing>>,
  'getBuyerDemands' : ActorMethod<[], Array<BuyerDemand>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommitments' : ActorMethod<[bigint], Array<Commitment>>,
  'getCommitmentsByBuyer' : ActorMethod<[], Array<Commitment>>,
  'getListingDetails' : ActorMethod<[bigint], HarvestListing>,
  'getSortedCommitments' : ActorMethod<[bigint], Array<Commitment>>,
  'getSortedListings' : ActorMethod<[], Array<HarvestListing>>,
  'getTransportOffers' : ActorMethod<[bigint], Array<TransportOffer>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'makeCommitment' : ActorMethod<[bigint, bigint, bigint], bigint>,
  'makeTransportOffer' : ActorMethod<
    [bigint, VehicleType, bigint, string, string],
    undefined
  >,
  'optimizeLogisticsRoutes' : ActorMethod<
    [bigint, VehicleType, string, string],
    Array<OptimizedRoute>
  >,
  'parseHarvestInput' : ActorMethod<[string], ParsedHarvestData>,
  'predictYieldAndPrice' : ActorMethod<
    [string, string, bigint, bigint, bigint],
    PredictYieldResult
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchListingsByCrop' : ActorMethod<[string], Array<HarvestListing>>,
  'updateTracking' : ActorMethod<[bigint, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];